name: Build and deploy app

on:
  push:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AZURE_WEBAPP_NAME: demo-webappsql-gh-actions-unique
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '6.0'
  AZURE_RESOURCEGROUP_NAME: demo-webappsql-gh-actions
  SQLSERVER_NAME: demo-webappsql-gh-actions-srv
  DATABASE_NAME: demo-webappsql-gh-actions-db
  SQLADMIN_LOGIN: 'Sqladminuser'
  SQLADMIN_PASS: 'P@ssw0rd123!'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build and publish
      run: |
        dotnet build --configuration Release
        dotnet publish -c Release -o myapp

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'

    - name: Create DB connection string
      run: |
        CONN_STR=$(az sql db show-connection-string --client ado.net --server ${{ env.SQLSERVER_NAME }} --name ${{ env.DATABASE_NAME }} -o tsv)
        CONN_STR=$(echo $CONN_STR | sed "s/<username>/${{ secrets.SQLADMIN_LOGIN }}/g")
        CONN_STR=$(echo $CONN_STR | sed "s/<password>/${{ secrets.SQLADMIN_PASS }}/g")
        echo "ConnectionStrings__MyDbConnection=$CONN_STR" >> $GITHUB_ENV

    - name: Update Database
      run: |
        dotnet tool restore
        dotnet ef database update
      env:
        ConnectionStrings__MyDbConnection: ${{ env.ConnectionStrings__MyDbConnection }}
