name: Build and deploy app

on:
  push:
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: demo-webappsql-gh-actions-unique
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '6.0'
  AZURE_RESOURCEGROUP_NAME: demo-webappsql-gh-actions
  SQLSERVER_NAME: demo-webappsql-gh-actions-srv
  DATABASE_NAME: demo-webappsql-gh-actions-db
  SQLADMIN_LOGIN: ${{ secrets.SQLADMIN_LOGIN }}
  SQLADMIN_PASS: ${{ secrets.SQLADMIN_PASS }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: dotnet build and publish
      run: |
        dotnet build --configuration Release
        dotnet publish -c Release -o myapp

    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'

    - name: create db connection string
      run: |
        CONN_STR=$(az sql db show-connection-string --client ado.net --server ${{ env.SQLSERVER_NAME }} --name ${{ env.DATABASE_NAME }} -o tsv)
        CONN_STR=$(echo $CONN_STR | sed "s/<username>/${{ env.SQLADMIN_LOGIN }}/g")
        CONN_STR=$(echo $CONN_STR | sed "s/<password>/${{ env.SQLADMIN_PASS }}/g")
        echo "SQL_DB_CONN_STR=$CONN_STR" >> $GITHUB_ENV

    - name: Update Database
      run: |
        dotnet tool install --global dotnet-ef --version 6.0.8
        dotnet ef database update
      env:
        ConnectionStrings__MyDbConnection: ${{ env.SQL_DB_CONN_STR }}
