name: Build and deploy app

on:
  push:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AZURE_WEBAPP_NAME: demo-webappsql-gh-actions-eastus
  AZURE_WEBAPP_PACKAGE_PATH: './publish'
  DOTNET_VERSION: '6.0'
  AZURE_RESOURCEGROUP_NAME: MyResourceGroup
  SQLSERVER_NAME: demo-webappsql-gh-actions-srv
  DATABASE_NAME: demo-webappsql-gh-actions-db
  SQLADMIN_LOGIN: 'Sqladminuser'
  SQLADMIN_PASS: 'P@ssw0rd123!'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SERVICE_PRINCIPAL }}

    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show

    - name: Azure PowerShell script
      uses: azure/powershell@v2
      with:
        azPSVersion: "latest"
        inlineScript: |
          Get-AzContext

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Install .NET Core 3.1 ASP.NET runtime
      run: |
        wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.de