name: Build and deploy app

on:
  push:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AZURE_WEBAPP_NAME: demo-webappsql-gh-actions-unique
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '6.0'
  AZURE_RESOURCEGROUP_NAME: demo-webappsql-gh-actions
  SQLSERVER_NAME: demo-webappsql-gh-actions-srv
  DATABASE_NAME: demo-webappsql-gh-actions-db
  SQLADMIN_LOGIN: 'Sqladminuser'
  SQLADMIN_PASS: 'P@ssw0rd123!'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true

    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show

    - name: Azure PowerShell script
      uses: azure/powershell@v2
      with:
        azPSVersion: "latest"
        inlineScript: |
          Get-AzContext

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Install .NET Core 3.1 ASP.NET runtime
      run: |
        wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        sudo apt-get update
        sudo apt-get install -y aspnetcore-runtime-3.1 dotnet-sdk-3.1

    - name: dotnet build and publish
      run: |
        dotnet build --configuration Release
        dotnet publish -c Release -o myapp

    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'

    - name: create db connection string
      run: |
        CONN_STR=$(az sql db show-connection-string --client ado.net --server ${{ env.SQLSERVER_NAME }} --name ${{ env.DATABASE_NAME }} -o tsv)
        CONN_STR=$(echo $CONN_STR | sed "s/<username>/${{ secrets.SQLADMIN_LOGIN }}/g")
        CONN_STR=$(echo $CONN_STR | sed "s/<password>/${{ secrets.SQLADMIN_PASS }}/g")
        echo "SQL_DB_CONN_STR=$CONN_STR" >> $GITHUB_ENV

    - name: Update Database
      run: |
        dotnet tool install --global dotnet-ef --version 6.0.8
        echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
        dotnet ef database update
      env:
        ConnectionStrings__MyDbConnection: ${{ env.SQL_DB_CONN_STR }}
